### ISSUE TITLE
bug: Source gem fails to build on aarch64-linux — crate not included in gem package

### ISSUE THREAD

**Issue by IBazylchuk** [Goldziher/html-to-markdown#325]
## Summary

The source distribution of `html-to-markdown` (`gem install html-to-markdown --platform=ruby`) fails to build on any platform that doesn't have a precompiled gem, because the Rust crate it depends on is not included in the packaged gem.

This affects all users on `aarch64-linux` (ARM64 Linux — common for AWS Graviton, Ampere, Oracle OCI, Hetzner ARM, self-hosted ARM CI runners), since no `aarch64-linux` precompiled gem is published to RubyGems.

Precompiled platforms currently on RubyGems for 3.2.4: `ruby` (source, broken), `x86_64-linux`, `arm64-darwin`.

## Reproduction

```bash
docker run --rm --platform linux/arm64 ruby:3.4.9-slim bash -c '
  apt-get update -qq && apt-get install -y -qq cargo build-essential && \
  gem install html-to-markdown -v 3.2.4 --platform=ruby
'
```

## What happens

```
current directory: /usr/local/bundle/gems/html-to-markdown-3.2.4/ext/html_to_markdown_rb
make
error: failed to load manifest for dependency `html-to-markdown-rs`
Caused by: failed to read `/usr/local/bundle/gems/html-to-markdown-3.2.4/ext/html_to_markdown_rb/../../../../crates/html-to-markdown/Cargo.toml`
```

## Root cause

`packages/ruby/ext/html_to_markdown_rb/Cargo.toml` (as of v3.3.3) contains:

```toml
[dependencies]
html-to-markdown-rs = { path = "../../../../crates/html-to-markdown", ... }
```

This path dependency resolves to the monorepo root (4 levels up from the gem's `ext/` directory). When the gem is packaged, `packages/ruby/html_to_markdown.gemspec` declares:

```ruby
spec.files = Dir.glob(%w[lib/**/* ext/**/* sig/**/*])
```

Only `lib/`, `ext/`, and `sig/` are included. The `crates/html-to-markdown/` directory in the monorepo root is **not** included in the packaged gem, so Cargo cannot resolve the path dependency at install time on end-user machines.

For comparison, version 3.1.0 vendored the crate as `vendor/html-to-markdown-rs/` inside the gem itself, and source builds worked. The regression was introduced when the Ruby binding was moved into the monorepo and switched from a vendored copy to a path dependency.

## Impact

- Any platform without a precompiled gem (notably `aarch64-linux`) cannot install `html-to-markdown >= 3.2.0`.
- The last working source build on RubyGems is `3.1.0`.
- Users on ARM64 Linux CI/production (AWS Graviton, Oracle OCI, Hetzner ARM, ARM-based self-hosted runners) are blocked from upgrading.

## Suggested fixes (pick one)

1. **Vendor the crate at build time.** Add a `rake` task that copies `crates/html-to-markdown/` into `packages/ruby/vendor/` and rewrites the path in `Cargo.toml` before `gem build`. Restores the pre-3.2.0 behavior.
2. **Include the crate in `spec.files`.** Glob the crate source and adjust the Cargo path at pack time:
   ```ruby
   spec.files = Dir.glob(%w[lib/**/* ext/**/* sig/**/* vendor/**/*])
   ```
   plus a pack-time step that stages `crates/html-to-markdown/` into `packages/ruby/vendor/`.
3. **Publish `aarch64-linux` precompiled gems.** `rb-sys-dock` / `rake-compiler-dock` supports cross-compilation for `aarch64-linux`. Adding it to the release matrix would also sidestep the source-build issue for affected users.

Option 3 is the most user-friendly (no Rust toolchain required on install). Option 1 or 2 is needed regardless, so that `--platform=ruby` actually works as a fallback.

## Additional note

Between v3.2.4 (the last Ruby release on RubyGems, 2026-04-17) and v3.3.3 (current, 2026-04-23), the monorepo changelog mentions Ruby-specific work (`Ruby RBS type stubs auto-generated via alef`, `Ruby Magnus binding — fixed 65 compilation errors`, `Ruby Rakefile — Bundler 4 compatibility`). None of this has been published to RubyGems. If the Ruby binding is currently in a broken state, a note in the README or a yanked 3.2.4 would help affected users downgrade deliberately rather than troubleshoot build failures.
