### ISSUE TITLE
bug: Cannot find native binding when running in Docker (Linux)

### ISSUE THREAD

**Issue by Codeshark-NET** [Goldziher/html-to-markdown#273]
Hi! After upgrading to v3, I'm getting the following error when running in a Docker container (Linux x64):
```																																							  
Error: Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). 
Please try `npm i` again after removing both package-lock.json and node_modules directory.
...
[cause]: Error: Cannot find module '@kreuzberg/html-to-markdown-node-linux-x64-gnu'
```

The lockfile is generated on Windows, then pnpm install --frozen-lockfile runs inside Docker. The Linux binary package (@kreuzberg/html-to-markdown-node-linux-x64-gnu) never makes it into the lockfile, so it's not available at runtime.

Worked around it for now by manually adding the Linux package to my own optionalDependencies, but that's a bit awkward. Is there a recommended way to handle this? Other packages I use declare their platform variants as optionalDependencies which lets pnpm handle it automatically. Not sure if that's intentional here or something that slipped through in v3.

Thanks for reading & thanks for the package, it works great beside this! 💪

**Comment by Goldziher** [comment]
Thanks for reporting. Will be fixed ASAP

**Comment by duwscan** [comment]
@Goldziher 
`error: Cannot find module './html-to-markdown-rs.node' from '/node_modules/@kreuzberg/html-to-markdown-node/index.js'
`
Hey i got this errr after bump to 3.2, does it related or because i'm using Bun

**Comment by Goldziher** [comment]
im aware. thanks!

**Comment by Goldziher** [comment]
hopefully will be fixed in next patch. will be released later today

**Comment by Goldziher** [comment]
this should be fixed. im closing lemme know if it persists.

**Comment by thanhnguyen2187** [comment]
Hi @Goldziher thanks for the work. I'm still having the problem with version `3.4.0-rc.16`. Can you double check?

**Comment by thanhnguyen2187** [comment]
For posterity, a workaround is to install `@kreuzberg/html-to-markdown-node-linux-x64-gnu`, then have this in `package.json`'s `script`

```json
{
  "//why postinstall": "Workaround https://github.com/kreuzberg-dev/html-to-markdown/issues/273",
  "postinstall": "cp node_modules/@kreuzberg/html-to-markdown-node-linux-x64-gnu/html-to-markdown-node.linux-x64-gnu.node node_modules/@kreuzberg/html-to-markdown-node/index.linux-x64-gnu.node"
}
```

**Comment by Goldziher** [comment]
Closing — the underlying cause is npm's [optional-dependency lockfile bug (npm/cli#4828)](https://github.com/npm/cli/issues/4828) and is not fixable in our package. The published package's `optionalDependencies` already declares all 9 supported platform variants, but npm/pnpm only resolve the one matching the lockfile-generation host, so a lockfile generated on Windows won't include the Linux native and a frozen install on Linux fails.

**Workaround for pnpm cross-platform Docker builds** (recommended): set `supportedArchitectures` so the lockfile resolves natives for every target — add to `pnpm-workspace.yaml` (or top of `package.json`):

```yaml
supportedArchitectures:
  os: [current, linux]
  cpu: [current, x64, arm64]
  libc: [current, glibc, musl]
```

Or pass per-install: `pnpm install --config.supported-architectures.os=linux --config.supported-architectures.cpu=x64`.

**For npm**: regenerate `package-lock.json` inside the target platform image, or add the platform package directly to your `dependencies` (e.g. `@kreuzberg/html-to-markdown-node-linux-x64-gnu`).

**For Bun**: same root cause; same workarounds apply.

This pattern matches every other prebuilt-native npm package (esbuild, @swc/core, sharp, …) and is documented at https://pnpm.io/settings#supportedarchitectures.

If you've already tried `supportedArchitectures` and it still fails on a recent release, please re-open with a minimal Dockerfile + `pnpm-lock.yaml` and I'll dig deeper.
